import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { PublicEnvScript } from "next-runtime-env";
import { LanguageProvider } from "@/src/contexts/LanguageContext";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

const prompt = localFont({
  src: [
    { path: './fonts/Prompt-Light.ttf', weight: '300', style: 'normal' },
    { path: './fonts/Prompt-Regular.ttf', weight: '400', style: 'normal' },
    { path: './fonts/Prompt-Medium.ttf', weight: '500', style: 'normal' },
    { path: './fonts/Prompt-Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-prompt',
  display: 'swap',
});

export const viewport = {
   width: "device-width",
   initialScale: 1,
   maximumScale: 1,
   userScalable: false,
};

export const metadata: Metadata = {
  title: "Please-Protect",
  description: "Generated by create next app",
  icons: {
    icon: "/please-protect.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <PublicEnvScript />
      </head>
      <body
        className={`${notoSansThai.variable} antialiased`}
      >
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}